const crypto = require("crypto");
const bcrypt = require("bcrypt");
const { supabase, supabaseAdmin, bucket } = require("../config/supabaseClient");

const saltRounds = 10;

// ─── Upload image to Supabase Storage ───────────────────────
const uploadImageToSupabase = async (file) => {
  if (!file) return null;

  const fileName = `${Date.now()}_${file.originalname}`;
  const { error: uploadError } = await supabaseAdmin.storage
    .from(bucket)
    .upload(fileName, file.buffer, {
      contentType: file.mimetype,
    });

  if (uploadError)
    throw new Error(`Image upload failed: ${uploadError.message}`);

  const { data } = supabaseAdmin.storage.from(bucket).getPublicUrl(fileName);
  return data.publicUrl;
};

// ─── Generate a cryptographically secure random password ─────
const generateSecurePassword = () =>
  crypto.randomBytes(18).toString("base64url");

// ─── 1. GET ALL ARTISTS ────────────────────────────────────
exports.getAllArtists = async (req, res) => {
  try {
    const { data, error } = await supabase
      .from("artists")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) throw error;
    res.status(200).json(data);
  } catch (err) {
    res.status(500).json({ error: "Failed to fetch artists." });
  }
};

// ─── 2. CREATE ARTIST ──────────────────────────────────────
exports.createArtist = async (req, res) => {
  try {
    const {
      name,
      genre,
      bio,
      email,
      password,
      phone,
      followers,
      profileUrl,
      spotifyUrl,
      instagramUrl,
      idDocumentUrl,
      status,
      verified,
      born_date,
      early_life,
      career,
      recognition_awards,
    } = req.body;

    // ── Validation ──
    if (!email || !name) {
      return res.status(400).json({ error: "Name and email are required." });
    }

    let finalPassword =
      password && password.trim() !== "" ? password.trim() : null;
    let autoGenerated = false;

    if (finalPassword && finalPassword.length < 8) {
      return res
        .status(400)
        .json({ error: "Password must be at least 8 characters." });
    }

    // ── Generate secure password if not provided ──
    if (!finalPassword) {
      finalPassword = generateSecurePassword();
      autoGenerated = true;
    }

    // ── STEP 1: Create user in Supabase Auth ──
    const { data: authData, error: authError } =
      await supabaseAdmin.auth.admin.createUser({
        email,
        password: finalPassword,
        email_confirm: true,
        user_metadata: { role: "artist", name },
      });

    if (authError) {
      if (authError.message.includes("already been registered")) {
        return res
          .status(409)
          .json({ error: "This email is already registered." });
      }
      return res.status(400).json({ error: "Failed to create auth account." });
    }

    const authUserId = authData.user.id;

    // ── STEP 2: Hash password for local reference ──
    const passwordHash = await bcrypt.hash(finalPassword, saltRounds);

    // ── STEP 3: Upload image if provided ──
    let imagePath = "https://picsum.photos/seed/default/300/300";
    if (req.file) {
      imagePath = await uploadImageToSupabase(req.file);
    }

    // ── STEP 4: Insert into artists table ──
    const artistData = {
      id: authUserId,
      name: name || null,
      genre: genre || null,
      image: imagePath,
      bio: bio || null,
      email: email || null,
      phone: phone || null,
      followers: followers || "0M",
      profile_url: profileUrl || null,
      spotify_url: spotifyUrl || null,
      instagram_url: instagramUrl || null,
      id_document_url: idDocumentUrl || null,
      status: status || "Pending",
      verified: verified === "true" || verified === true || false,
      born_date: born_date || null,
      early_life: early_life || null,
      career: career || null,
      recognition_awards: recognition_awards || null,
      language: null,
      role: "artist",
      password_hash: passwordHash,
    };

    const { data: artist, error: dbError } = await supabaseAdmin
      .from("artists")
      .insert([artistData])
      .select();

    if (dbError) {
      // Rollback: delete the auth user to prevent orphaned account
      await supabaseAdmin.auth.admin.deleteUser(authUserId);
      return res.status(500).json({ error: "Failed to create artist record." });
    }

    // ── STEP 5: Send password reset link if password was auto-generated ──
    if (autoGenerated) {
      try {
        await supabaseAdmin.auth.admin.generateLink({
          type: "recovery",
          email,
        });
      } catch (linkErr) {
        // Non-critical — artist can request reset manually
      }
    }

    res.status(201).json({
      success: true,
      artist: artist[0],
      passwordAutoGenerated: autoGenerated,
    });
  } catch (err) {
    res.status(500).json({ error: "Internal server error." });
  }
};

// ─── 3. UPDATE ARTIST ──────────────────────────────────────
exports.updateArtist = async (req, res) => {
  try {
    const { id } = req.params;

    // ── Check if artist exists ──
    const { data: existingArtist, error: checkError } = await supabaseAdmin
      .from("artists")
      .select("id")
      .eq("id", id)
      .single();

    if (checkError || !existingArtist) {
      return res.status(404).json({ error: "Artist not found." });
    }

    const {
      name,
      genre,
      bio,
      email,
      password,
      phone,
      followers,
      profileUrl,
      spotifyUrl,
      instagramUrl,
      idDocumentUrl,
      status,
      verified,
      born_date,
      early_life,
      career,
      recognition_awards,
    } = req.body;

    // ── Password validation ──
    if (password && password.trim() !== "" && password.trim().length < 8) {
      return res
        .status(400)
        .json({ error: "Password must be at least 8 characters." });
    }

    // ── Update Supabase Auth if email or password changed ──
    const authUpdateData = {};
    if (email) authUpdateData.email = email;
    if (password && password.trim() !== "") {
      authUpdateData.password = password.trim();
    }

    if (Object.keys(authUpdateData).length > 0) {
      try {
        await supabaseAdmin.auth.admin.updateUserById(id, authUpdateData);
      } catch (authErr) {
        // Auth update failed — continue with DB update
      }
    }

    // ── Hash new password if provided ──
    let passwordHash = null;
    if (password && password.trim() !== "") {
      passwordHash = await bcrypt.hash(password.trim(), saltRounds);
    }

    // ── Upload new image if provided ──
    let imagePath;
    if (req.file) {
      imagePath = await uploadImageToSupabase(req.file);
    }

    // ── Build update object (only include provided fields) ──
    const updateData = {};
    if (name !== undefined) updateData.name = name;
    if (genre !== undefined) updateData.genre = genre;
    if (bio !== undefined) updateData.bio = bio;
    if (email !== undefined) updateData.email = email;
    if (phone !== undefined) updateData.phone = phone;
    if (followers !== undefined) updateData.followers = followers;
    if (profileUrl !== undefined) updateData.profile_url = profileUrl;
    if (spotifyUrl !== undefined) updateData.spotify_url = spotifyUrl;
    if (instagramUrl !== undefined) updateData.instagram_url = instagramUrl;
    if (idDocumentUrl !== undefined) updateData.id_document_url = idDocumentUrl;
    if (status !== undefined) updateData.status = status;
    if (verified !== undefined) {
      updateData.verified = verified === "true" || verified === true;
    }
    if (born_date !== undefined) updateData.born_date = born_date || null;
    if (early_life !== undefined) updateData.early_life = early_life || null;
    if (career !== undefined) updateData.career = career || null;
    if (recognition_awards !== undefined) {
      updateData.recognition_awards = recognition_awards || null;
    }
    if (passwordHash) updateData.password_hash = passwordHash;
    if (imagePath) updateData.image = imagePath;

    // ── Execute update ──
    const { data, error } = await supabaseAdmin
      .from("artists")
      .update(updateData)
      .eq("id", id)
      .select();

    if (error) {
      return res.status(500).json({ error: "Failed to update artist." });
    }

    if (!data || data.length === 0) {
      return res.status(404).json({ error: "Artist not found." });
    }

    res.status(200).json({ success: true, artist: data[0] });
  } catch (err) {
    res.status(500).json({ error: "Internal server error." });
  }
};

// ─── 4. DELETE ARTIST ──────────────────────────────────────
exports.deleteArtist = async (req, res) => {
  try {
    const { id } = req.params;

    // ── Check if artist exists ──
    const { data: existingArtist, error: checkError } = await supabaseAdmin
      .from("artists")
      .select("id")
      .eq("id", id)
      .single();

    if (checkError || !existingArtist) {
      return res.status(404).json({ error: "Artist not found." });
    }

    // ── Delete from database ──
    const { error: dbError } = await supabaseAdmin
      .from("artists")
      .delete()
      .eq("id", id);

    if (dbError) {
      return res.status(500).json({ error: "Failed to delete artist." });
    }

    // ── Delete from Supabase Auth ──
    try {
      await supabaseAdmin.auth.admin.deleteUser(id);
    } catch (authErr) {
      // Auth user might already be deleted — non-critical
    }

    res
      .status(200)
      .json({ success: true, message: "Artist deleted successfully." });
  } catch (err) {
    res.status(500).json({ error: "Internal server error." });
  }
};
