const crypto = require("crypto");
const bcrypt = require("bcrypt");
const fs = require("fs");
const { supabase, supabaseAdmin, bucket } = require("../config/supabaseClient");

const saltRounds = 10;


const uploadImageToSupabase = async (file) => {
  if (!file) return null;

  let fileBuffer = file.buffer;

  // Fallback: disk storage middleware gives a path instead of a buffer
  if (!fileBuffer && file.path) {
    fileBuffer = fs.readFileSync(file.path);
  }

  if (!fileBuffer) {
    throw new Error(
      "Uploaded file has no readable data (check your multer storage config).",
    );
  }

  const fileName = `${Date.now()}_${file.originalname}`;
  const { error: uploadError } = await supabaseAdmin.storage
    .from(bucket)
    .upload(fileName, fileBuffer, { contentType: file.mimetype });

  // Clean up temp disk file if multer wrote one
  if (file.path) {
    fs.unlink(file.path, () => {});
  }

  if (uploadError)
    throw new Error(`Image upload failed: ${uploadError.message}`);

  const { data } = supabaseAdmin.storage.from(bucket).getPublicUrl(fileName);
  return data.publicUrl;
};

const generateSecurePassword = () =>
  crypto.randomBytes(18).toString("base64url");

// ─── GET ALL ARTISTS (optional ?status=Pending) ───
exports.getAllArtists = async (req, res) => {
  try {
    const { status } = req.query;
    let query = supabase.from("artists").select("*");
    if (status) query = query.eq("status", status);
    const { data, error } = await query.order("created_at", {
      ascending: false,
    });
    if (error) throw error;
    res.status(200).json(data);
  } catch (err) {
    console.error("Fetch Artists Error:", err);
    res
      .status(500)
      .json({ error: "Failed to fetch artists.", details: err.message });
  }
};

// ─── CHECK CURRENT USER'S OWN ARTIST STATUS ────────────────
exports.getMyArtistStatus = async (req, res) => {
  try {
    const userId = req.user.id;

    const { data, error } = await supabaseAdmin
      .from("artists")
      .select("id, name, status, verified, created_at")
      .eq("id", userId)
      .maybeSingle();

    if (error) throw error;

    if (!data) {
      return res.status(200).json({ exists: false });
    }

    res.status(200).json({
      exists: true,
      status: data.status,
      verified: data.verified,
      name: data.name,
    });
  } catch (err) {
    console.error("Get My Artist Status Error:", err);
    res
      .status(500)
      .json({ error: "Failed to check artist status.", details: err.message });
  }
};

// ─── ADMIN DIRECTLY CREATES A VERIFIED ARTIST ───
exports.createArtist = async (req, res) => {
  try {
    const {
      name,
      genre,
      language,
      bio,
      email,
      password,
      phone,
      followers,
      profile_url,
      spotifyUrl,
      instagramUrl,
      idDocumentUrl,
      status,
      verified,
      born_date,
      early_life,
      career,
      recognition_awards,
    } = req.body;

    if (!email || !name) {
      return res.status(400).json({ error: "Name and email are required." });
    }

    let finalPassword =
      password && password.trim() !== "" ? password.trim() : null;
    let autoGenerated = false;

    if (finalPassword && finalPassword.length < 8) {
      return res
        .status(400)
        .json({ error: "Password must be at least 8 characters." });
    }
    if (!finalPassword) {
      finalPassword = generateSecurePassword();
      autoGenerated = true;
    }

    const { data: authData, error: authError } =
      await supabaseAdmin.auth.admin.createUser({
        email,
        password: finalPassword,
        email_confirm: true,
        user_metadata: { role: "artist", name },
      });

    if (authError) {
      console.error("Supabase Auth Error:", authError);
      if (authError.message.includes("already been registered")) {
        return res.status(409).json({
          error:
            "This email is already registered. Ask the user to submit a 'Become an Artist' request instead.",
        });
      }
      return res.status(400).json({
        error: "Failed to create auth account.",
        details: authError.message,
      });
    }

    const authUserId = authData.user.id;
    const passwordHash = await bcrypt.hash(finalPassword, saltRounds);

    let imagePath = "https://picsum.photos/seed/default/300/300";
    if (req.file) {
      try {
        imagePath = await uploadImageToSupabase(req.file);
      } catch (uploadErr) {
        console.error("Image Upload Error:", uploadErr);
      }
    }

    const artistData = {
      id: authUserId,
      name: name || null,
      genre: genre || null,
      language: language || null,
      image: imagePath,
      bio: bio || null,
      email: email || null,
      phone: phone || null,
      followers: followers || "0",
      profile_url: profile_url || null,
      spotify_url: spotifyUrl || null,
      instagram_url: instagramUrl || null,
      id_document_url: idDocumentUrl || null,
      status: status || "Verified",
      verified: verified === "true" || verified === true || true,
      born_date: born_date || null,
      early_life: early_life || null,
      career: career || null,
      recognition_awards: recognition_awards || null,
      password_hash: passwordHash,
    };

    const { data: artist, error: dbError } = await supabaseAdmin
      .from("artists")
      .insert([artistData])
      .select();

    if (dbError) {
      console.error("Database Insert Error:", dbError);
      await supabaseAdmin.auth.admin.deleteUser(authUserId);
      return res.status(500).json({
        error: "Failed to create artist record in database.",
        details: dbError.message,
      });
    }

    const { error: userRoleError } = await supabaseAdmin
      .from("users")
      .upsert({ id: authUserId, email, role: "artist" }, { onConflict: "id" });
    if (userRoleError)
      console.error("Failed to set user role:", userRoleError.message);

    if (autoGenerated) {
      try {
        await supabaseAdmin.auth.admin.generateLink({
          type: "recovery",
          email,
        });
      } catch (linkErr) {}
    }

    res.status(201).json({
      success: true,
      artist: artist[0],
      passwordAutoGenerated: autoGenerated,
    });
  } catch (err) {
    console.error("!!! CREATE ARTIST SERVER ERROR !!!", err);
    res.status(500).json({
      error: "Internal server error.",
      details: err?.message || JSON.stringify(err),
    });
  }
};

// ─── USER SUBMITS "BECOME AN ARTIST" REQUEST ───
exports.createArtistRequest = async (req, res) => {
  try {
    const userId = req.user.id;
    const userEmail = req.user.email;

    const {
      name,
      genre,
      language,
      bio,
      phone,
      born_date,
      early_life,
      career,
      recognition_awards,
      profile_url,
      idDocumentUrl,
    } = req.body;

    if (!name) {
      return res.status(400).json({ error: "Artist name is required." });
    }

    const { data: existing, error: existingError } = await supabaseAdmin
      .from("artists")
      .select("id, status")
      .eq("id", userId)
      .maybeSingle();

    if (existingError) throw existingError;

    if (existing) {
      const msg =
        existing.status === "Pending"
          ? "You already have an artist request pending review."
          : existing.status === "Verified"
            ? "You are already a verified artist."
            : "You already have an artist profile on file.";
      return res.status(409).json({ error: msg });
    }

    let imagePath = "https://picsum.photos/seed/default/300/300";
    if (req.file) {
      try {
        imagePath = await uploadImageToSupabase(req.file);
      } catch (uploadErr) {
        console.error("Image Upload Error:", uploadErr);
      }
    }

    const artistData = {
      id: userId,
      name,
      genre: genre || null,
      language: language || null,
      image: imagePath,
      bio: bio || null,
      email: userEmail,
      phone: phone || null,
      followers: "0",
      profile_url: profile_url || null,
      id_document_url: idDocumentUrl || null,
      status: "Pending",
      verified: false,
      born_date: born_date || null,
      early_life: early_life || null,
      career: career || null,
      recognition_awards: recognition_awards || null,
    };

    const { data: artist, error: dbError } = await supabaseAdmin
      .from("artists")
      .insert([artistData])
      .select();

    if (dbError) {
      console.error("Artist Request DB Error:", dbError);
      return res.status(500).json({
        error: "Failed to submit artist request.",
        details: dbError.message,
      });
    }

    res.status(201).json({ success: true, artist: artist[0] });
  } catch (err) {
    console.error("Create Artist Request Error:", err);
    res
      .status(500)
      .json({ error: "Internal server error.", details: err.message });
  }
};

// ─── ADMIN APPROVES A PENDING REQUEST ───
exports.approveArtistRequest = async (req, res) => {
  try {
    const { id } = req.params;

    const { data: existingArtist, error: checkError } = await supabaseAdmin
      .from("artists")
      .select("id, status, email")
      .eq("id", id)
      .maybeSingle();

    if (checkError) throw checkError;
    if (!existingArtist) {
      return res.status(404).json({ error: "Artist request not found." });
    }
    if (existingArtist.status === "Verified") {
      return res.status(409).json({ error: "Artist is already verified." });
    }

    const { data: updatedArtist, error: updateError } = await supabaseAdmin
      .from("artists")
      .update({ status: "Verified", verified: true })
      .eq("id", id)
      .select();

    if (updateError) {
      console.error("Approve Artist DB Error:", updateError);
      return res.status(500).json({
        error: "Failed to approve artist.",
        details: updateError.message,
      });
    }

    // ✅ FIXED: upsert instead of update — if this artist has no matching
    // row yet in "users" table (e.g. they never logged in via the normal
    // login flow before submitting their artist request), a plain
    // .update() silently affects 0 rows and their role never gets synced.
    const { error: roleError } = await supabaseAdmin
      .from("users")
      .upsert(
        { id, email: existingArtist.email, role: "artist" },
        { onConflict: "id" },
      );
    if (roleError)
      console.error(
        "Failed to update user role on approve:",
        roleError.message,
      );

    res.status(200).json({ success: true, artist: updatedArtist[0] });
  } catch (err) {
    console.error("Approve Artist Server Error:", err);
    res
      .status(500)
      .json({ error: "Internal server error.", details: err.message });
  }
};

// ─── ADMIN REJECTS A PENDING REQUEST ───
exports.rejectArtistRequest = async (req, res) => {
  try {
    const { id } = req.params;
    const { reason } = req.body;

    const { data: existingArtist, error: checkError } = await supabaseAdmin
      .from("artists")
      .select("id, status")
      .eq("id", id)
      .maybeSingle();

    if (checkError) throw checkError;
    if (!existingArtist) {
      return res.status(404).json({ error: "Artist request not found." });
    }

    const { data: updatedArtist, error: updateError } = await supabaseAdmin
      .from("artists")
      .update({ status: "Rejected", rejection_reason: reason || null })
      .eq("id", id)
      .select();

    if (updateError) {
      console.error("Reject Artist DB Error:", updateError);
      return res.status(500).json({
        error: "Failed to reject artist.",
        details: updateError.message,
      });
    }

    res.status(200).json({ success: true, artist: updatedArtist[0] });
  } catch (err) {
    console.error("Reject Artist Server Error:", err);
    res
      .status(500)
      .json({ error: "Internal server error.", details: err.message });
  }
};

// ─── UPDATE ARTIST ───
exports.updateArtist = async (req, res) => {
  try {
    const { id } = req.params;

    const { data: existingArtist, error: checkError } = await supabaseAdmin
      .from("artists")
      .select("id")
      .eq("id", id)
      .single();

    if (checkError || !existingArtist) {
      return res.status(404).json({ error: "Artist not found." });
    }

    const {
      name,
      genre,
      language,
      bio,
      email,
      password,
      phone,
      followers,
      profile_url,
      spotifyUrl,
      instagramUrl,
      idDocumentUrl,
      status,
      verified,
      born_date,
      early_life,
      career,
      recognition_awards,
    } = req.body;

    if (password && password.trim() !== "" && password.trim().length < 8) {
      return res
        .status(400)
        .json({ error: "Password must be at least 8 characters." });
    }

    const authUpdateData = {};
    if (email) authUpdateData.email = email;
    if (password && password.trim() !== "")
      authUpdateData.password = password.trim();

    if (Object.keys(authUpdateData).length > 0) {
      try {
        await supabaseAdmin.auth.admin.updateUserById(id, authUpdateData);
      } catch (authErr) {
        console.error("Auth Update Error:", authErr);
      }
    }

    let passwordHash = null;
    if (password && password.trim() !== "") {
      passwordHash = await bcrypt.hash(password.trim(), saltRounds);
    }

    // ✅ FIXED: image upload is now wrapped in try/catch. Previously, if
    // uploadImageToSupabase threw (e.g. because of a multer/storage
    // mismatch), this error propagated straight up and crashed the ENTIRE
    // request with a 500 — meaning status/verified changes sent in the
    // same request (e.g. approving via the edit modal) were never saved
    // either, since the DB update below never even ran.
    let imagePath;
    if (req.file) {
      try {
        imagePath = await uploadImageToSupabase(req.file);
      } catch (uploadErr) {
        console.error("Image Upload Error (update):", uploadErr);
        // Don't kill the whole update — just skip the image change and
        // continue saving everything else (status, verified, etc.)
      }
    }

    const updateData = {};
    if (name !== undefined) updateData.name = name;
    if (genre !== undefined) updateData.genre = genre;
    if (language !== undefined) updateData.language = language;
    if (bio !== undefined) updateData.bio = bio;
    if (email !== undefined) updateData.email = email;
    if (phone !== undefined) updateData.phone = phone;
    if (followers !== undefined) updateData.followers = followers;
    if (profile_url !== undefined) updateData.profile_url = profile_url;
    if (spotifyUrl !== undefined) updateData.spotify_url = spotifyUrl;
    if (instagramUrl !== undefined) updateData.instagram_url = instagramUrl;
    if (idDocumentUrl !== undefined) updateData.id_document_url = idDocumentUrl;
    if (status !== undefined) updateData.status = status;
    if (verified !== undefined)
      updateData.verified = verified === "true" || verified === true;
    if (born_date !== undefined) updateData.born_date = born_date || null;
    if (early_life !== undefined) updateData.early_life = early_life || null;
    if (career !== undefined) updateData.career = career || null;
    if (recognition_awards !== undefined)
      updateData.recognition_awards = recognition_awards || null;
    if (passwordHash) updateData.password_hash = passwordHash;
    if (imagePath) updateData.image = imagePath;

    const { data, error } = await supabaseAdmin
      .from("artists")
      .update(updateData)
      .eq("id", id)
      .select();

    if (error) {
      console.error("Database Update Error:", error);
      return res
        .status(500)
        .json({ error: "Failed to update artist.", details: error.message });
    }
    if (!data || data.length === 0) {
      return res.status(404).json({ error: "Artist not found." });
    }

    if (email !== undefined) {
      const { error: userSyncError } = await supabaseAdmin
        .from("users")
        .update({ email })
        .eq("id", id);
      if (userSyncError)
        console.error("Failed to sync email:", userSyncError.message);
    }

    res.status(200).json({ success: true, artist: data[0] });
  } catch (err) {
    console.error("Update Artist Server Error:", err);
    res
      .status(500)
      .json({ error: "Internal server error.", details: err.message });
  }
};

// ─── DELETE ARTIST ───
exports.deleteArtist = async (req, res) => {
  try {
    const { id } = req.params;

    const { data: existingArtist, error: checkError } = await supabaseAdmin
      .from("artists")
      .select("id")
      .eq("id", id)
      .single();

    if (checkError || !existingArtist) {
      return res.status(404).json({ error: "Artist not found." });
    }

    const { error: dbError } = await supabaseAdmin
      .from("artists")
      .delete()
      .eq("id", id);

    if (dbError) {
      console.error("Database Delete Error:", dbError);
      return res
        .status(500)
        .json({ error: "Failed to delete artist.", details: dbError.message });
    }

    try {
      await supabaseAdmin.auth.admin.deleteUser(id);
    } catch (authErr) {}

    res
      .status(200)
      .json({ success: true, message: "Artist deleted successfully." });
  } catch (err) {
    console.error("Delete Artist Server Error:", err);
    res
      .status(500)
      .json({ error: "Internal server error.", details: err.message });
  }
};
