const subgenres = {
  Alternative: [
    { value: "1", text: "Alternative" },
    { value: "27", text: "Alternative - Electronic / EBM" },
    { value: "359", text: "Alternative - Emo Punk" },
    { value: "19", text: "Alternative - Gothic" },
    { value: "20", text: "Alternative - Grunge" },
    { value: "21", text: "Alternative - Indie Pop" },
    { value: "22", text: "Alternative - Indie Rock" },
    { value: "360", text: "Alternative - Latin" },
    { value: "361", text: "Alternative - Latin Ska" },
    { value: "24", text: "Alternative - New Wave" },
    { value: "357", text: "Alternative - Pop Punk" },
    { value: "358", text: "Alternative - Post Punk" },
    { value: "25", text: "Alternative - Punk" },
    { value: "26", text: "Alternative - Ska" },
  ],
  African: [
    { value: "429", text: "African" },
    { value: "504", text: "African - Afrikaans" },
    { value: "505", text: "African - Afro Bashment" },
    { value: "507", text: "African - Afro Pop" },
    { value: "508", text: "African - Afro Soul" },
    { value: "509", text: "African - Afro Trap" },
    { value: "506", text: "African - Afro Urbain" },
    { value: "762", text: "African - Afrobeat" },
    { value: "510", text: "African - Assiko" },
    { value: "511", text: "African - Bend-Skin" },
    { value: "512", text: "African - Benga" },
    { value: "513", text: "African - Bikutsi" },
    { value: "514", text: "African - Bongo-Flava" },
    { value: "515", text: "African - Coupé Décalé" },
    { value: "517", text: "African - Gospel" },
    { value: "516", text: "African - Gqom" },
    { value: "518", text: "African - Highlife / Hiplife" },
    { value: "519", text: "African - Jùjú music" },
    { value: "520", text: "African - Kizomba" },
    { value: "521", text: "African - Kuduro" },
    { value: "522", text: "African - Kwaito" },
    { value: "523", text: "African - Makossa" },
    { value: "524", text: "African - Mandingue" },
    { value: "526", text: "African - Maskandi" },
    { value: "525", text: "African - Mbalax" },
    { value: "527", text: "African - Ndombolo" },
    { value: "528", text: "African - RPK / Rap" },
    { value: "529", text: "African - Rumba Congolaise" },
    { value: "532", text: "African - Shangaan Electro" },
    { value: "530", text: "African - Soukouss" },
    { value: "531", text: "African - Taarab" },
    { value: "533", text: "African - Yoruba" },
    { value: "534", text: "African - Zouglou" },
  ],
  Arabic: [
    { value: "431", text: "Arabic" },
    { value: "537", text: "Arabic - Algerian Raï" },
    { value: "535", text: "Arabic - Amazigh" },
    { value: "763", text: "Arabic - Arabesque" },
    { value: "552", text: "Arabic - Egyptian Chaabiat" },
    { value: "555", text: "Arabic - Egyptian Folk El Kaf Aswani" },
    { value: "553", text: "Arabic - Egyptian Folk Nubian" },
    { value: "554", text: "Arabic - Egyptian Folk Saidi" },
    { value: "559", text: "Arabic - Egyptian Indie" },
    { value: "556", text: "Arabic - Egyptian Mahraganat" },
    { value: "561", text: "Arabic - Egyptian Musicals" },
    { value: "564", text: "Arabic - Egyptian Operette" },
    { value: "551", text: "Arabic - Egyptian Patriotic" },
    { value: "562", text: "Arabic - Egyptian Plays" },
    { value: "550", text: "Arabic - Egyptian Satire" },
    { value: "560", text: "Arabic - Egyptian Soundtrack" },
    { value: "557", text: "Arabic - Egyptian Tarab Classical" },
    { value: "558", text: "Arabic - Egyptian Tarab Pop" },
    { value: "563", text: "Arabic - Egyptian TV Shows" },
    { value: "503", text: "Arabic - Electronic Dance Music" },
    { value: "536", text: "Arabic - Indie" },
    { value: "568", text: "Arabic - Iraqi Folk Dabka" },
    { value: "569", text: "Arabic - Iraqi Folk Khachaba" },
    { value: "567", text: "Arabic - Iraqi Folk Maqam" },
    { value: "566", text: "Arabic - Iraqi Folk Mawaweel" },
    { value: "565", text: "Arabic - Iraqi Folk Radeh" },
    { value: "574", text: "Arabic - Iraqi Indie" },
    { value: "576", text: "Arabic - Iraqi Musicals" },
    { value: "579", text: "Arabic - Iraqi Operette" },
    { value: "571", text: "Arabic - Iraqi Patriotic" },
    { value: "577", text: "Arabic - Iraqi Plays" },
    { value: "570", text: "Arabic - Iraqi Satire" },
    { value: "575", text: "Arabic - Iraqi Soundtrack" },
    { value: "572", text: "Arabic - Iraqi Tarab Classical" },
    { value: "573", text: "Arabic - Iraqi Tarab Pop" },
    { value: "578", text: "Arabic - Iraqi TV Shows" },
    { value: "764", text: "Arabic - Islamic" },
    { value: "543", text: "Arabic - Islamic Anasheed" },
    { value: "539", text: "Arabic - Islamic Chant" },
    { value: "540", text: "Arabic - Islamic Quran" },
    { value: "544", text: "Arabic - Islamic Ramadan" },
    { value: "541", text: "Arabic - Islamic Recital" },
    { value: "542", text: "Arabic - Islamic Speeches" },
    { value: "765", text: "Arabic - Khaleeji" },
    { value: "586", text: "Arabic - Khaleeji Folk Shakshaka" },
    { value: "587", text: "Arabic - Khaleeji Folk Swahili" },
    { value: "584", text: "Arabic - Khaleeji Indie" },
    { value: "589", text: "Arabic - Khaleeji Musicals" },
    { value: "592", text: "Arabic - Khaleeji Operette" },
    { value: "581", text: "Arabic - Khaleeji Patriotic" },
    { value: "590", text: "Arabic - Khaleeji Plays" },
    { value: "580", text: "Arabic - Khaleeji Satire" },
    { value: "585", text: "Arabic - Khaleeji Shayla" },
    { value: "588", text: "Arabic - Khaleeji Soundtrack" },
    { value: "582", text: "Arabic - Khaleeji Tarab Classical" },
    { value: "583", text: "Arabic - Khaleeji Tarab Pop" },
    { value: "591", text: "Arabic - Khaleeji TV Shows" },
    { value: "549", text: "Arabic - Kurdi" },
    { value: "595", text: "Arabic - Lebanese Folk Ataba & Mijana" },
    { value: "596", text: "Arabic - Lebanese Folk Dabke" },
    { value: "597", text: "Arabic - Lebanese Folk Zajal" },
    { value: "600", text: "Arabic - Lebanese Indie" },
    { value: "602", text: "Arabic - Lebanese Musicals" },
    { value: "605", text: "Arabic - Lebanese Operette" },
    { value: "594", text: "Arabic - Lebanese Patriotic" },
    { value: "603", text: "Arabic - Lebanese Plays" },
    { value: "593", text: "Arabic - Lebanese Satire" },
    { value: "601", text: "Arabic - Lebanese Soundtrack" },
    { value: "598", text: "Arabic - Lebanese Tarab Classical" },
    { value: "599", text: "Arabic - Lebanese Tarab Pop" },
    { value: "604", text: "Arabic - Lebanese TV Shows" },
    { value: "611", text: "Arabic - Levantine Folk Bedouin" },
    { value: "612", text: "Arabic - Levantine Folk New Dabke Syrian" },
    { value: "613", text: "Arabic - Levantine Folk Qoudud & Muwashahat" },
    { value: "610", text: "Arabic - Levantine Indie" },
    { value: "615", text: "Arabic - Levantine Musicals" },
    { value: "618", text: "Arabic - Levantine Operette" },
    { value: "607", text: "Arabic - Levantine Patriotic" },
    { value: "616", text: "Arabic - Levantine Plays" },
    { value: "606", text: "Arabic - Levantine Satire" },
    { value: "614", text: "Arabic - Levantine Soundtrack" },
    { value: "608", text: "Arabic - Levantine Tarab Classical" },
    { value: "609", text: "Arabic - Levantine Tarab Pop" },
    { value: "617", text: "Arabic - Levantine TV Shows" },
    { value: "545", text: "Arabic - Maalaya Folk Dagni" },
    { value: "546", text: "Arabic - Moroccan Chaabi" },
    { value: "547", text: "Arabic - Moroccan Raï" },
    { value: "548", text: "Arabic - Moroccan Sahraoui" },
    { value: "766", text: "Arabic - North African" },
    { value: "624", text: "Arabic - North African Folk Andalusi" },
    { value: "626", text: "Arabic - North African Folk Gnawa" },
    { value: "627", text: "Arabic - North African Folk Mezwed" },
    { value: "628", text: "Arabic - North African Folk Rif" },
    { value: "623", text: "Arabic - North African Indie" },
    { value: "630", text: "Arabic - North African Musicals" },
    { value: "633", text: "Arabic - North African Operette" },
    { value: "620", text: "Arabic - North African Patriotic" },
    { value: "631", text: "Arabic - North African Plays" },
    { value: "625", text: "Arabic - North African Raï Classical" },
    { value: "619", text: "Arabic - North African Satire" },
    { value: "629", text: "Arabic - North African Soundtrack" },
    { value: "621", text: "Arabic - North African Tarab Classical" },
    { value: "622", text: "Arabic - North African Tarab Pop" },
    { value: "632", text: "Arabic - North African TV Shows" },
    { value: "767", text: "Arabic - Raï" },
    { value: "538", text: "Arabic - Soufi" },
    { value: "639", text: "Arabic - Sudanese Folk Swahili" },
    { value: "638", text: "Arabic - Sudanese Indie" },
    { value: "641", text: "Arabic - Sudanese Musicals" },
    { value: "644", text: "Arabic - Sudanese Operette" },
    { value: "635", text: "Arabic - Sudanese Patriotic" },
    { value: "642", text: "Arabic - Sudanese Plays" },
    { value: "634", text: "Arabic - Sudanese Satire" },
    { value: "640", text: "Arabic - Sudanese Soundtrack" },
    { value: "636", text: "Arabic - Sudanese Tarab Classical" },
    { value: "637", text: "Arabic - Sudanese Tarab Pop" },
    { value: "643", text: "Arabic - Sudanese TV Shows" },
    { value: "647", text: "Arabic - Yemeni Folk Hadramawti" },
    { value: "651", text: "Arabic - Yemeni Folk Swahili" },
    { value: "650", text: "Arabic - Yemeni Indie" },
    { value: "653", text: "Arabic - Yemeni Musicals" },
    { value: "656", text: "Arabic - Yemeni Operette" },
    { value: "646", text: "Arabic - Yemeni Patriotic" },
    { value: "654", text: "Arabic - Yemeni Plays" },
    { value: "645", text: "Arabic - Yemeni Satire" },
    { value: "652", text: "Arabic - Yemeni Soundtrack" },
    { value: "648", text: "Arabic - Yemeni Tarab Classical" },
    { value: "649", text: "Arabic - Yemeni Tarab Pop" },
    { value: "655", text: "Arabic - Yemeni TV Shows" },
  ],
  Asian: [
    { value: "430", text: "Asian" },
    { value: "778", text: "Asian - Chinese" },
    { value: "780", text: "Asian - Chinese / Tibetan Native" },
    { value: "779", text: "Asian - Chinese Folk" },
    { value: "694", text: "Asian - Filipino / Bikol" },
    { value: "695", text: "Asian - Filipino / Cebuano" },
    { value: "702", text: "Asian - Filipino / Chavacano" },
    { value: "697", text: "Asian - Filipino / Ilocano" },
    { value: "698", text: "Asian - Filipino / Kapampangan" },
    { value: "696", text: "Asian - Filipino / llonggo" },
    { value: "699", text: "Asian - Filipino / Pangasinan" },
    { value: "700", text: "Asian - Filipino / Tagalog" },
    { value: "701", text: "Asian - Filipino / Waray" },
    { value: "692", text: "Asian - Hong Kongese" },
    { value: "688", text: "Asian - Indonesian" },
    { value: "691", text: "Asian - Indonesian / Christian Pop" },
    { value: "690", text: "Asian - Indonesian / Keroncong" },
    { value: "689", text: "Asian - Indonesian / Koplo" },
    { value: "783", text: "Asian - Indonesian / Religious" },
    { value: "782", text: "Asian - Japanese" },
    { value: "857", text: "Asian - Japanese - Enka" },
    { value: "858", text: "Asian - Japanese - Enka - Kayokyoku" },
    { value: "781", text: "Asian - Korean" },
    { value: "667", text: "Asian - Malaysian" },
    { value: "670", text: "Asian - Malaysian / Chinese New Year" },
    { value: "668", text: "Asian - Malaysian / Christmas" },
    { value: "672", text: "Asian - Malaysian / Deepavali" },
    { value: "669", text: "Asian - Malaysian / Hari Raya" },
    { value: "671", text: "Asian - Malaysian / Traditional" },
    { value: "703", text: "Asian - OPM / 70’s Pinoy Music" },
    { value: "704", text: "Asian - OPM / 80’s Pinoy Music" },
    { value: "705", text: "Asian - OPM / 90’s Pinoy Music" },
    { value: "706", text: "Asian - OPM / Bisrock" },
    { value: "707", text: "Asian - OPM / Cebuano" },
    { value: "708", text: "Asian - OPM / Chavacano" },
    { value: "709", text: "Asian - OPM / Folk Songs / Country Music" },
    { value: "710", text: "Asian - OPM / Harana & Kundiman" },
    { value: "711", text: "Asian - OPM / Hiligaynon" },
    { value: "712", text: "Asian - OPM / Ilocano" },
    { value: "716", text: "Asian - OPM / Kapampangan" },
    { value: "713", text: "Asian - OPM / Pinoy Acoustic" },
    { value: "714", text: "Asian - OPM / Pinoy Ballad" },
    { value: "715", text: "Asian - OPM / Pinoy Love Songs" },
    { value: "717", text: "Asian - Pinoy Rock" },
    { value: "693", text: "Asian - Taiwanese" },
    { value: "784", text: "Asian - Taiwanese Folk" },
    { value: "661", text: "Asian - Thaï" },
    { value: "666", text: "Asian - Thaï / Folk Music" },
    { value: "663", text: "Asian - Thaï / Luk-Krung" },
    { value: "662", text: "Asian - Thaï / Luk-Thung" },
    { value: "664", text: "Asian - Thaï / Mo-Lam" },
    { value: "665", text: "Asian - Thaï / Song For Life" },
    { value: "673", text: "Asian - Vietnamese" },
    { value: "686", text: "Asian - Vietnamese / Bài tròi" },
    { value: "674", text: "Asian - Vietnamese / Bolero" },
    { value: "681", text: "Asian - Vietnamese / Ca Trù" },
    { value: "675", text: "Asian - Vietnamese / Cải Lương" },
    { value: "678", text: "Asian - Vietnamese / Chèo" },
    { value: "685", text: "Asian - Vietnamese / Đình Huế" },
    { value: "676", text: "Asian - Vietnamese / Đờn Ca Tài Tử" },
    { value: "683", text: "Asian - Vietnamese / Hò Huế" },
    { value: "687", text: "Asian - Vietnamese / Lý" },
    { value: "684", text: "Asian - Vietnamese / Nhạc Cung" },
    { value: "677", text: "Asian - Vietnamese / Quan Họ" },
    { value: "682", text: "Asian - Vietnamese / Trầu Văn" },
    { value: "679", text: "Asian - Vietnamese / Tuồng" },
    { value: "680", text: "Asian - Vietnamese / Xẩm" },
  ],
  Blues: [
    { value: "2", text: "Blues" },
    { value: "33", text: "Blues - Contemporary Blues" },
    { value: "36", text: "Blues - Traditional Blues" },
  ],
  Brazilian: [
    { value: "433", text: "Brazilian" },
    { value: "657", text: "Brazilian - Arrocha" },
    { value: "768", text: "Brazilian - Axe" },
    { value: "658", text: "Brazilian - Baiao" },
    { value: "769", text: "Brazilian - Baile Funk" },
    { value: "770", text: "Brazilian - Bossa Nova" },
    { value: "660", text: "Brazilian - Brega" },
    { value: "801", text: "Brazilian - Calypso" },
    { value: "771", text: "Brazilian - Choro" },
    { value: "772", text: "Brazilian - Forro" },
    { value: "773", text: "Brazilian - Frevo" },
    { value: "659", text: "Brazilian - Lambada" },
    { value: "774", text: "Brazilian - MPB" },
    { value: "775", text: "Brazilian - Pagode" },
    { value: "776", text: "Brazilian - Samba" },
    { value: "777", text: "Brazilian - Sertanejo" },
  ],

  children_music: [
    { value: "3", text: "Children Music" },
    { value: "38", text: "Children Music - Holiday" },
    { value: "37", text: "Children Music - Lullabies" },
    { value: "40", text: "Children Music - Stories" },
  ],
  christian_gospel: [
    { value: "9", text: "Christian & Gospel" },
    { value: "462", text: "Christian & Gospel - Arabic" },
    { value: "463", text: "Christian & Gospel - Arabic / Byzantine Chant" },
    { value: "464", text: "Christian & Gospel - Arabic / Christmas" },
    { value: "465", text: "Christian & Gospel - Arabic / Taranim & Tarateel" },
    { value: "342", text: "Christian & Gospel - Brazilian Gospel" },
    { value: "116", text: "Christian & Gospel - Christian" },
    { value: "118", text: "Christian & Gospel - Gospel" },
    { value: "117", text: "Christian & Gospel - Praise & Worship" },
  ],

  Classical: [
    { value: "4", text: "Classical" },
    { value: "269", text: "Classical - Ballet" },
    { value: "39", text: "Classical - Baroque" },
    { value: "42", text: "Classical - Chamber" },
    { value: "274", text: "Classical - Choral" },
    { value: "270", text: "Classical - Concerto" },
    { value: "295", text: "Classical - Contemporary Era" },
    { value: "275", text: "Classical - Crossover" },
    { value: "276", text: "Classical - Early Music" },
    { value: "296", text: "Classical - Electronic" },
    { value: "277", text: "Classical - High Classical" },
    { value: "278", text: "Classical - Impressionist" },
    { value: "279", text: "Classical - Medieval" },
    { value: "280", text: "Classical - Minimalism" },
    { value: "44", text: "Classical - Modern Compositions" },
    { value: "45", text: "Classical - Opera" },
    { value: "46", text: "Classical - Orchestral" },
    { value: "272", text: "Classical - Religious" },
    { value: "281", text: "Classical - Renaissance" },
    { value: "47", text: "Classical - Romantic" },
    { value: "294", text: "Classical - Solo Instrumental" },
    { value: "48", text: "Classical - Solo Piano" },
  ],

  Country: [
    { value: "5", text: "Country" },
    { value: "50", text: "Country - Contemporary" },
    { value: "53", text: "Country - Pop" },
    { value: "55", text: "Country - Traditional" },
  ],
  Dance: [
    { value: "6", text: "Dance" },
    { value: "74", text: "Dance - Acid House" },
    { value: "343", text: "Dance - Afro House" },
    { value: "850", text: "Dance - Amapiano" },
    { value: "362", text: "Dance - Bass House" },
    { value: "75", text: "Dance - Big Room" },
    { value: "57", text: "Dance - Breaks" },
    { value: "78", text: "Dance - Classic House" },
    { value: "80", text: "Dance - Deep House" },
    { value: "435", text: "Dance - Detroit Techno" },
    { value: "363", text: "Dance - Disco Polo" },
    { value: "63", text: "Dance - DJ Mix" },
    { value: "64", text: "Dance - Down Beat / Trip Hop" },
    { value: "58", text: "Dance - Drum & Bass" },
    { value: "59", text: "Dance - Drum & Bass / Jungle" },
    { value: "65", text: "Dance - Dub" },
    { value: "60", text: "Dance - EDM / Commercial" },
    { value: "66", text: "Dance - Electro" },
    { value: "843", text: "Dance - Electro House" },
    { value: "364", text: "Dance - Funky / Groove / Jackin' House" },
    { value: "323", text: "Dance - Future House" },
    { value: "73", text: "Dance - Garage / Bassline / Grime" },
    { value: "365", text: "Dance - Hard Dance" },
    { value: "849", text: "Dance - Hard Techno" },
    { value: "247", text: "Dance - Hardcore" },
    { value: "72", text: "Dance - House" },
    { value: "802", text: "Dance - House - Organic / Downtempo" },
    { value: "366", text: "Dance - Indie Dance" },
    { value: "87", text: "Dance - Latin House" },
    { value: "842", text: "Dance - Mainstage" },
    { value: "346", text: "Dance - Melodic House & Techno" },
    { value: "67", text: "Dance - Minimal / Deep Tech" },
    { value: "856", text: "Dance - New Trance" },
    { value: "82", text: "Dance - Nu Disco / Disco" },
    { value: "88", text: "Dance - Progressive House" },
    { value: "102", text: "Dance - Psytrance" },
    { value: "853", text: "Dance - Rave" },
    { value: "89", text: "Dance - Soulful House" },
    { value: "90", text: "Dance - Tech House" },
    { value: "95", text: "Dance - Techno" },
    { value: "840", text: "Dance - techno - Deep" },
    { value: "803", text: "Dance - Techno - Driving" },
    { value: "98", text: "Dance - Trance" },
    { value: "324", text: "Dance - Tropical House" },
  ],

  easyListening: [
    { value: "7", text: "Easy Listening" },
    { value: "106", text: "Easy Listening - Lounge" },
    { value: "367", text: "Easy Listening - Swing" },
    { value: "297", text: "Easy Listening - Vocal" },
  ],
  Electronic: [
    { value: "354", text: "Electronic" },
    { value: "436", text: "Electronic - Ambient" },
    { value: "841", text: "Electronic - Deep Dubstep / Grime" },
    { value: "496", text: "Electronic - Dubstep" },
    { value: "437", text: "Electronic - Electronica / Downtempo" },
    { value: "497", text: "Electronic - Experimental / Noise" },
    { value: "500", text: "Electronic - Lounge / Chillout" },
    { value: "855", text: "Electronic - Phonk" },
    { value: "499", text: "Electronic - Trap / Future Bass" },
  ],
  Folk: [
    { value: "356", text: "Folk" },
    { value: "438", text: "Folk - Acoustic Folk" },
    { value: "439", text: "Folk - Contemporary Folk" },
    { value: "440", text: "Folk - Indie Folk" },
    { value: "441", text: "Folk - Pop Folk" },
  ],
  hipHopRap: [
    { value: "8", text: "Hip Hop/Rap" },
    { value: "851", text: "Hip Hop/Rap - African Drill" },
    { value: "852", text: "Hip Hop/Rap - African Hip Hop" },
    { value: "457", text: "Hip Hop/Rap - Algerian Hip Hop" },
    { value: "108", text: "Hip Hop/Rap - Alternative" },
    { value: "455", text: "Hip Hop/Rap - Arabic Hip Hop" },
    { value: "341", text: "Hip Hop/Rap - Brazilian Hip Hop" },
    { value: "452", text: "Hip Hop/Rap - Canadian / Indigenous Hip Hop" },
    { value: "305", text: "Hip Hop/Rap - Chinese Hip Hop" },
    { value: "450", text: "Hip Hop/Rap - Cloud Rap / Sad Rap" },
    { value: "110", text: "Hip Hop/Rap - DJ Mix" },
    { value: "449", text: "Hip Hop/Rap - Dutch Hip Hop" },
    { value: "111", text: "Hip Hop/Rap - French Hip Hop" },
    { value: "443", text: "Hip Hop/Rap - French Trap" },
    { value: "112", text: "Hip Hop/Rap - German Hip Hop" },
    { value: "442", text: "Hip Hop/Rap - Grime" },
    { value: "446", text: "Hip Hop/Rap - Italian Hip Hop" },
    { value: "451", text: "Hip Hop/Rap - Jazz Hip Hop" },
    { value: "458", text: "Hip Hop/Rap - Khaleeji Hip Hop" },
    { value: "113", text: "Hip Hop/Rap - Latin Hip Hop" },
    { value: "445", text: "Hip Hop/Rap - Latin Trap" },
    { value: "844", text: "Hip Hop/Rap - LoFi" },
    { value: "459", text: "Hip Hop/Rap - Moroccan Hip Hop" },
    { value: "460", text: "Hip Hop/Rap - North African Hip Hop" },
    { value: "114", text: "Hip Hop/Rap - Old School Hip Hop" },
    { value: "444", text: "Hip Hop/Rap - Pop Urbaine" },
    { value: "115", text: "Hip Hop/Rap - Raggaeton" },
    { value: "845", text: "Hip Hop/Rap - Russian Hip Hop" },
    { value: "447", text: "Hip Hop/Rap - Swedish Hip Hop" },
    { value: "454", text: "Hip Hop/Rap - Taiwanese Hip Hop" },
    { value: "453", text: "Hip Hop/Rap - Thaï Hip Hop" },
    { value: "348", text: "Hip Hop/Rap - Trap" },
    { value: "461", text: "Hip Hop/Rap - Tunisian Hip Hop" },
    { value: "456", text: "Hip Hop/Rap - Turkish Hip Hop" },
    { value: "448", text: "Hip Hop/Rap - UK Hip Hop" },
  ],
  Indian: [
    { value: "432", text: "Indian" },
    { value: "719", text: "Indian - Assamese" },
    { value: "720", text: "Indian - Assamese Soundtrack" },
    { value: "721", text: "Indian - Bengali" },
    { value: "722", text: "Indian - Bengali Soundtrack" },
    { value: "723", text: "Indian - Bhangra" },
    { value: "754", text: "Indian - Bhojpuri" },
    { value: "755", text: "Indian - Bhojpuri Soundtrack" },
    { value: "785", text: "Indian - Bollywood" },
    { value: "738", text: "Indian - Carnatic Classical" },
    { value: "739", text: "Indian - Carnatic Classical Instrumental" },
    { value: "747", text: "Indian - Children Song" },
    { value: "787", text: "Indian - Classical" },
    { value: "788", text: "Indian - Classical / Instrumental" },
    { value: "789", text: "Indian - Classical / Vocal" },
    { value: "800", text: "Indian - Devotional & Spiritual" },
    { value: "744", text: "Indian - Dialogue" },
    { value: "724", text: "Indian - DJ" },
    { value: "790", text: "Indian - Folk" },
    { value: "725", text: "Indian - Fusion" },
    { value: "786", text: "Indian - Gazal" },
    { value: "726", text: "Indian - Gujarati" },
    { value: "727", text: "Indian - Gujarati Soundtrack" },
    { value: "752", text: "Indian - Haryanvi" },
    { value: "753", text: "Indian - Haryanvi Soundtrack" },
    { value: "728", text: "Indian - Hindi" },
    { value: "730", text: "Indian - Hindi Non Soundtrack" },
    { value: "729", text: "Indian - Hindi Soundtrack" },
    { value: "740", text: "Indian - Hindustani Classical" },
    { value: "741", text: "Indian - Hindustani Classical Instrumental" },
    { value: "743", text: "Indian - Indigenous" },
    { value: "731", text: "Indian - Kannada" },
    { value: "732", text: "Indian - Kannada Soundtrack" },
    { value: "733", text: "Indian - Konkani" },
    { value: "734", text: "Indian - Malayalam" },
    { value: "735", text: "Indian - Malayalam Soundtrack" },
    { value: "748", text: "Indian - Mappila" },
    { value: "736", text: "Indian - Marathi" },
    { value: "737", text: "Indian - Marathi Soundtrack" },
    { value: "760", text: "Indian - Odia" },
    { value: "761", text: "Indian - Odia Soundtrack" },
    { value: "745", text: "Indian - Poetry" },
    { value: "791", text: "Indian - Pop & Fusion" },
    { value: "792", text: "Indian - Punjabi" },
    { value: "718", text: "Indian - Punjabi Soundtrack" },
    { value: "793", text: "Indian - Rabindra Sangeet" },
    { value: "750", text: "Indian - Rajasthani" },
    { value: "751", text: "Indian - Rajasthani Soundtrack" },
    { value: "794", text: "Indian - Regional Indian" },
    { value: "795", text: "Indian - Regional Indian Soundtrack" },
    { value: "758", text: "Indian - Sanskrit" },
    { value: "759", text: "Indian - Sanskrit Soundtrack" },
    { value: "746", text: "Indian - Speech" },
    { value: "742", text: "Indian - Sufi" },
    { value: "796", text: "Indian - Tamil" },
    { value: "797", text: "Indian - Tamil Soundtrack" },
    { value: "798", text: "Indian - Telugu" },
    { value: "799", text: "Indian - Telugu Soundtrack" },
    { value: "749", text: "Indian - Traditional" },
    { value: "756", text: "Indian - Urdu" },
    { value: "757", text: "Indian - Urdu Soundtrack" },
  ],
  Jazz: [
    { value: "10", text: "Jazz" },
    { value: "121", text: "Jazz - Bebop" },
    { value: "122", text: "Jazz - Big Band" },
    { value: "123", text: "Jazz - Classic" },
    { value: "124", text: "Jazz - Contemporary" },
    { value: "125", text: "Jazz - Dixie / Rag Time" },
    { value: "126", text: "Jazz - Free Jazz" },
    { value: "127", text: "Jazz - Fusion" },
    { value: "128", text: "Jazz - Jazz Funk" },
    { value: "129", text: "Jazz - Latin Jazz" },
    { value: "130", text: "Jazz - Nu Jazz / Acid Jazz" },
    { value: "368", text: "Jazz - Oriental Jazz" },
    { value: "131", text: "Jazz - Smooth Jazz" },
    { value: "132", text: "Jazz - Swing" },
    { value: "133", text: "Jazz - Traditional" },
    { value: "134", text: "Jazz - World" },
  ],
  Latin: [
    { value: "11", text: "Latin" },
    { value: "374", text: "Latin - Argentine Cuarteto" },
    { value: "373", text: "Latin - Argentine Cumbia" },
    { value: "372", text: "Latin - Argentine Folklore" },
    { value: "317", text: "Latin - Baladas" },
    { value: "421", text: "Latin - Boleros" },
    { value: "135", text: "Latin - Bossa Nova" },
    { value: "422", text: "Latin - Caribbean" },
    { value: "378", text: "Latin - Caribbean / Kompa" },
    {
      value: "377",
      text: "Latin - Caribbean / Traditional / Biguine / Mazurka",
    },
    { value: "376", text: "Latin - Caribbean / Zouk" },
    { value: "423", text: "Latin - Cuban" },
    { value: "369", text: "Latin - Ranchera" },
    { value: "370", text: "Latin - Reggaeton" },
    { value: "318", text: "Latin - Regional Mexicano" },
    { value: "139", text: "Latin - Salsa / Merengue" },
    { value: "371", text: "Latin - Son Jarocho" },
    { value: "375", text: "Latin - Tango" },
    { value: "136", text: "Latin - Tropical" },
    { value: "140", text: "Latin - Urban" },
  ],
  Metal: [
    { value: "355", text: "Metal" },
    { value: "468", text: "Metal - Black Metal" },
    { value: "469", text: "Metal - Death Metal" },
    { value: "470", text: "Metal - Deathcore" },
    { value: "486", text: "Metal - Djent" },
    { value: "471", text: "Metal - Doom" },
    { value: "472", text: "Metal - Folk Metal" },
    { value: "473", text: "Metal - Goth" },
    { value: "481", text: "Metal - Grindcore" },
    { value: "501", text: "Metal - Hard Rock" },
    { value: "474", text: "Metal - Hardcore" },
    { value: "502", text: "Metal - Heavy metal" },
    { value: "475", text: "Metal - Industrial" },
    { value: "476", text: "Metal - Metalcore" },
    { value: "485", text: "Metal - Nu Metal" },
    { value: "477", text: "Metal - Post Black" },
    { value: "478", text: "Metal - Power Metal" },
    { value: "480", text: "Metal - Prog Folk" },
    { value: "479", text: "Metal - Proggressive Metal" },
    { value: "482", text: "Metal - Sludge" },
    { value: "483", text: "Metal - Symphonic Metal" },
    { value: "484", text: "Metal - Thrash Metal" },
  ],
  Pop: [
    { value: "13", text: "Pop" },
    { value: "164", text: "Pop - Alternative" },
    { value: "425", text: "Pop - Arabic" },
    { value: "396", text: "Pop - Batak" },
    { value: "388", text: "Pop - Brazilian" },
    { value: "410", text: "Pop - Canadian / Indigenous" },
    { value: "303", text: "Pop - Cantopop" },
    { value: "384", text: "Pop - Chinese Ethno Pop" },
    { value: "390", text: "Pop - Colombian" },
    { value: "165", text: "Pop - Contemporary / Adult" },
    { value: "166", text: "Pop - Dance" },
    { value: "424", text: "Pop - Dangdut" },
    { value: "382", text: "Pop - Dutch" },
    { value: "400", text: "Pop - Egyptian" },
    { value: "379", text: "Pop - Electropop" },
    { value: "168", text: "Pop - Folk" },
    { value: "167", text: "Pop - French" },
    { value: "380", text: "Pop - French / Variété Française" },
    { value: "381", text: "Pop - French Zouk" },
    { value: "169", text: "Pop - German" },
    { value: "398", text: "Pop - Hokkien / Tawainese" },
    { value: "854", text: "Pop - Hyperpop" },
    { value: "394", text: "Pop - Indie" },
    { value: "393", text: "Pop - Indonesian" },
    { value: "401", text: "Pop - Iraqi" },
    { value: "408", text: "Pop - Islamic Pop / Arabic" },
    { value: "409", text: "Pop - Islamic Pop / Indonesian" },
    { value: "170", text: "Pop - Italo" },
    { value: "312", text: "Pop - J-Pop" },
    { value: "392", text: "Pop - Jawa" },
    { value: "325", text: "Pop - K-Pop" },
    { value: "402", text: "Pop - Khaleeji" },
    { value: "171", text: "Pop - Latin" },
    { value: "403", text: "Pop - Lebanese" },
    { value: "404", text: "Pop - Levantine" },
    { value: "385", text: "Pop - Malaysian Indo" },
    { value: "301", text: "Pop - Mandopop" },
    { value: "387", text: "Pop - Manele" },
    { value: "391", text: "Pop - Mexican" },
    { value: "397", text: "Pop - Minang" },
    { value: "386", text: "Pop - Mizrahi" },
    { value: "405", text: "Pop - North African" },
    { value: "328", text: "Pop - Pinoy" },
    { value: "172", text: "Pop - R&B" },
    { value: "174", text: "Pop - Rock" },
    { value: "428", text: "Pop - Russian Chanson" },
    { value: "427", text: "Pop - Schlager" },
    { value: "389", text: "Pop - Sertanejo Universitario" },
    { value: "175", text: "Pop - Singer Songwriter" },
    { value: "176", text: "Pop - Spanish" },
    { value: "406", text: "Pop - Sudanese" },
    { value: "395", text: "Pop - Sunda" },
    { value: "383", text: "Pop - Swedish" },
    { value: "329", text: "Pop - Thai" },
    { value: "399", text: "Pop - Turkish" },
    { value: "407", text: "Pop - Yemeni" },
  ],
  RB_Soul: [
    { value: "14", text: "R&B/Soul" },
    { value: "466", text: "R&B/Soul - Arabic" },
    { value: "177", text: "R&B/Soul - Contemporary" },
    { value: "178", text: "R&B/Soul - Disco" },
    { value: "179", text: "R&B/Soul - Funk & Soul" },
    { value: "183", text: "R&B/Soul - Hip Hop" },
    { value: "467", text: "R&B/Soul - Latin" },
  ],
  Reggae: [
    { value: "15", text: "Reggae" },
    { value: "411", text: "Reggae - Brazilian Reggae" },
    { value: "413", text: "Reggae - Caribbean Dancehall" },
    { value: "412", text: "Reggae - Caribbean Reggae" },
    { value: "185", text: "Reggae - Dancehall" },
    { value: "186", text: "Reggae - Dub" },
    { value: "187", text: "Reggae - Roots" },
  ],
  Relaxation: [
    { value: "28", text: "Relaxation" },
    { value: "434", text: "Relaxation - Bali Spa" },
    { value: "29", text: "Relaxation - Meditation" },
    { value: "31", text: "Relaxation - World" },
  ],
  Rock: [
    { value: "16", text: "Rock" },
    { value: "188", text: "Rock - Alternative" },
    { value: "189", text: "Rock - Brit-Pop Rock" },
    { value: "190", text: "Rock - Classic" },
    { value: "419", text: "Rock - Experimental" },
    { value: "191", text: "Rock - Folk Rock" },
    { value: "414", text: "Rock - Garage" },
    { value: "192", text: "Rock - German Rock" },
    { value: "420", text: "Rock - J-Rock" },
    { value: "426", text: "Rock - Latin Rock" },
    { value: "418", text: "Rock - Noise Rock" },
    { value: "416", text: "Rock - Post Rock" },
    { value: "196", text: "Rock - Progressive" },
    { value: "415", text: "Rock - Psychedelic" },
    { value: "197", text: "Rock - Rock 'n' Roll" },
    { value: "300", text: "Rock - Rockabilly" },
    { value: "846", text: "Rock - Russian Rock" },
    { value: "417", text: "Rock - Shoegazing" },
    { value: "198", text: "Rock - Singer / Songwriter" },
  ],
  Various: [
    { value: "12", text: "Various" },
    { value: "141", text: "Various - Audiobook" },
    { value: "142", text: "Various - Audiobook / Children" },
    { value: "143", text: "Various - Audiobook / Comedy" },
    { value: "144", text: "Various - Audiobook / Documentation / Discovery" },
    { value: "145", text: "Various - Audiobook / Fiction" },
    { value: "146", text: "Various - Audiobook / Guide" },
    { value: "147", text: "Various - Audiobook / Historical" },
    { value: "149", text: "Various - Audiobook / Novel" },
    { value: "150", text: "Various - Audiobook / Theatre" },
    { value: "151", text: "Various - Comedy" },
    { value: "265", text: "Various - Fitness & Workout" },
    { value: "152", text: "Various - Holiday" },
    { value: "153", text: "Various - Holiday / Christmas" },
    { value: "154", text: "Various - Karaoke" },
    { value: "155", text: "Various - Radio Show" },
    { value: "848", text: "Various - Radio Show - Hörspiele" },
    { value: "156", text: "Various - Sound Effects" },
    { value: "157", text: "Various - Soundtrack" },
    { value: "847", text: "Various - Soundtrack - Anime" },
    { value: "158", text: "Various - Soundtrack / Children" },
    { value: "159", text: "Various - Soundtrack / Movie" },
    { value: "160", text: "Various - Soundtrack / Musical" },
    { value: "161", text: "Various - Soundtrack / TV" },
    { value: "162", text: "Various - Speeches / Spoken Word" },
  ],
  worldMusic: [
    { value: "17", text: "World Music / Regional Folklore" },
    { value: "204", text: "World Music / Regional Folklore - Australian" },
    { value: "205", text: "World Music / Regional Folklore - Cajun / Creole" },
    {
      value: "208",
      text: "World Music / Regional Folklore - Eastern European",
    },
    { value: "209", text: "World Music / Regional Folklore - Ethnic" },
    { value: "313", text: "World Music / Regional Folklore - Farsi" },
    { value: "316", text: "World Music / Regional Folklore - Flamenco" },
    { value: "210", text: "World Music / Regional Folklore - French" },
    {
      value: "233",
      text: "World Music / Regional Folklore - German / Volksmusik",
    },
    { value: "219", text: "World Music / Regional Folklore - Greek" },
    {
      value: "494",
      text: "World Music / Regional Folklore - Indian Ocean / Maloya",
    },
    {
      value: "495",
      text: "World Music / Regional Folklore - Indian Ocean / Séga",
    },
    { value: "216", text: "World Music / Regional Folklore - Irish / Celtic" },
    { value: "220", text: "World Music / Regional Folklore - Italian" },
    { value: "489", text: "World Music / Regional Folklore - Jewish Music" },
    { value: "217", text: "World Music / Regional Folklore - Klezmer" },
    { value: "218", text: "World Music / Regional Folklore - Mediterranean" },
    { value: "490", text: "World Music / Regional Folklore - Mizrahi" },
    { value: "223", text: "World Music / Regional Folklore - Nordic" },
    { value: "224", text: "World Music / Regional Folklore - North American" },
    { value: "225", text: "World Music / Regional Folklore - Pacific Island" },
    { value: "493", text: "World Music / Regional Folklore - Polish" },
    { value: "491", text: "World Music / Regional Folklore - Russian Folk" },
    { value: "492", text: "World Music / Regional Folklore - Russian Poetry" },
    { value: "221", text: "World Music / Regional Folklore - Spanish" },
    { value: "262", text: "World Music / Regional Folklore - Sufi & Ghazals" },
    {
      value: "487",
      text: "World Music / Regional Folklore - Turkish / Fantezi",
    },
    { value: "263", text: "World Music / Regional Folklore - Turkish / Halk" },
    { value: "264", text: "World Music / Regional Folklore - Turkish / Sanat" },
    { value: "488", text: "World Music / Regional Folklore - Turkish / Özgün" },
    { value: "231", text: "World Music / Regional Folklore - Western Europe" },
    { value: "232", text: "World Music / Regional Folklore - Worldbeat" },
  ],
};


export const genres = Object.keys(subgenres);
export const getSubgenres = (genre) => {
  return subgenres[genre] || [];
};

// You can export if using modules:
// export default musicGenres;
// You can export if using modules:
